spring.application.name=order-service
# path of the Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# by-default values are true only, so we can even skip below configs
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#for service discovery
product.service.baseurl=http://product-service

#rate limiter

# bucket filled with 2 tokens every 10 second,
# if there is no token wait for 1 sec before rejecting the request
#initially2 to,ken allow and when 2 req done new come wait for 0 s and
# immediae give fallback if 5 s then for 5 s and chk token ava but token availa is 20s
resilience4j.ratelimiter.instances.productRateLimiter.limitForPeriod=2
#If there is no token available, don't wait at all. Reject the request immediately and invoke the fallback.
resilience4j.ratelimiter.instances.productRateLimiter.timeoutDuration=5s

#bucket refileld after 20 s
resilience4j.ratelimiter.instances.productRateLimiter.limitRefreshPeriod=60s
